### ISSUE TITLE
electrs occasionally crashes due to EWOULDBLOCK

### ISSUE THREAD

**Issue by wiz** [mempool/electrs#4]
```
thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }) }called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }) }thread '', thread 'thread 'thread 'tokio-runtime-workertokio-runtime-workerthread '' panicked at 'tokio-runtime-workercalled `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }) }' panicked at 'thread 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }) }thread 'tokio-runtime-workerthread '' panicked at 'thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/new_index/schema.rscalled `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }) }tokio-runtime-worker', thread 'src/new_index/schema.rs' panicked at 'tokio-runtime-workercalled `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }) }' panicked at ':called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }) }1034', :10src/new_index/schema.rs
', note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
:src/new_index/schema.rs' panicked at ':tokio-runtime-worker1034called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/new_index/schema.rs:thread 'thread 'tokio-runtime-worker:1034:tokio-runtime-workerthread '' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }) }thread '' panicked at 'tokio-runtime-workerthread ':thread '' panicked at 'tokio-runtime-workercalled `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/new_index/schema.rs:1034:thread '10tokio-runtime-worker' panicked at '
called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/new_index/schema.rs:1034:10
' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', thread '', tokio-runtime-worker' panicked at 'src/new_index/schema.rscalled `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }) }:', 1034src/new_index/schema.rs::101034
:10
tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/new_index/schema.rs:1034:10
', src/new_index/schema.rs:1034:10
called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', src/new_index/schema.rs:1034:10
tokio-runtime-workersrc/new_index/schema.rs1034tokio-runtime-workerthread '10' panicked at '', ', tokio-runtime-workersrc/new_index/schema.rs101034
```

**Comment by wiz** [comment]
https://stackoverflow.com/questions/56916161/how-to-deal-with-wouldblock-error-with-a-tokio-tcplistener

**Comment by wiz** [comment]
solution is to increase `kern.threads.max_threads_per_proc` on FreeBSD from default of 1500 to a very high number

**Comment by wiz** [comment]
also need to set num_threads to 0 in line 1034 of src/new_index/schema.rs

**Comment by wiz** [comment]
nevermind I guess 0 is best for CPU bound and 16 best for SSD bound ? https://docs.rs/rayon/latest/rayon/struct.ThreadPoolBuilder.html
